const authRoutes = require("../routes/authRoutes");
const subscriptionRoutes = require("../routes/subscriptionRoutes");
const packageRoutes = require("../routes/packageRoutes");
const accountRoutes = require("../routes/accountRoutes");
const userRoutes = require("../routes/userRoutes");
const compoundRoutes = require("../routes/compoundRoutes");
const estateRoutes = require("../routes/estateRoutes");
const contactRoutes = require("../routes/contactRoutes");
const brokerContactRoutes = require("../routes/brokerContactRoutes");
const landlordContactRoutes = require("../routes/landlordContactRoutes");
const serviceContactRoutes = require("../routes/serviceContactRoutes");
const tenantContactRoutes = require("../routes/tenantContactRoutes");
const tagRoutes = require("../routes/tagRoutes");
const contractRoutes = require("../routes/contractRoutes");
const revenueRoutes = require("../routes/revenueRoutes");
const expenseRoutes = require("../routes/expenseRoutes");
const taskRoutes = require("../routes/taskRoutes");
const reportRoutes = require("../routes/reportRoutes");
const statsRoutes = require("../routes/statsRoutes");
const configRoutes = require("../routes/configRoutes");
const testimonialRoutes = require("../routes/testimonialRoutes");
const supportRoutes = require("../routes/supportRoutes");
const termRoutes = require("../routes/termRoutes");

const mountRoutes = (app) => {
  app.use("/api/v1/auth", authRoutes);
  app.use("/api/v1/subscriptions", subscriptionRoutes);
  app.use("/api/v1/packages", packageRoutes);
  app.use("/api/v1/accounts", accountRoutes);
  app.use("/api/v1/users", userRoutes);
  app.use("/api/v1/compounds", compoundRoutes);
  app.use("/api/v1/estates", estateRoutes);
  app.use("/api/v1/estates/:estateId/contracts", contractRoutes);
  app.use("/api/v1/estates/:estateId/revenues", revenueRoutes);
  app.use("/api/v1/contacts", contactRoutes);
  app.use("/api/v1/contacts/brokers", brokerContactRoutes);
  app.use("/api/v1/contacts/landlords", landlordContactRoutes);
  app.use("/api/v1/contacts/services", serviceContactRoutes);
  app.use("/api/v1/contacts/tenants", tenantContactRoutes);
  app.use("/api/v1/tags", tagRoutes);
  app.use("/api/v1/expenses", expenseRoutes);
  app.use("/api/v1/tasks", taskRoutes);
  app.use("/api/v1/reports", reportRoutes);
  app.use("/api/v1/stats", statsRoutes);
  app.use("/api/v1/configs", configRoutes);
  app.use("/api/v1/testimonials", testimonialRoutes);
  app.use("/api/v1/support", supportRoutes);
  app.use("/api/v1/terms", termRoutes);
};

module.exports = mountRoutes;
